steps:
  - id: 'build'
    name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true","appengine:deploy"]
  - id: 'attest'
    name: 'gcr.io/$PROJECT_ID/binauthz-attestation:latest'
    args:
      - '--artifact-url'
      - 'eu.gcr.io/$PROJECT_ID/appengine/default.4:latest'
      - '--attestor'
      - 'projects/$PROJECT_ID/attestors/cluster-approved'
      - '--keyversion'
      - 'projects/gitlab-poc-284212/locations/global/keyRings/devops-poc/cryptoKeys/attestator-code-metrics/cryptoKeyVersions/1'