steps:
  - id: 'build'
    name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - id: 'sonarqube'
    name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
    args:
    - '-Dsonar.host.url=https://sonarcloud.io'
    - '-Dsonar.login=54de221eb33acd02aeca8cccb537e3bd747fcb78'
    - '-Dsonar.projectKey=ilgatnau_demo-2T-AppEngine'
    - '-Dsonar.organization=ilgatnau'
    - '-Dsonar.sources=./src/main/java'
  - id: 'attest-sonarqube'
    name: 'gcr.io/$PROJECT_ID/binauthz-attestation:latest'
    args:
      - '--artifact-url'
      - 'jenkins/jenkins:lts'
      - '--attestor'
      - 'projects/$PROJECT_ID/attestors/cluster-approved'
      - '--keyversion'
      - 'projects/gitlab-poc-284212/locations/global/keyRings/devops-poc/cryptoKeys/attestator-code-metrics/cryptoKeyVersions/1'
  - id: 'deploy'
    name: maven:3-jdk-8
    entrypoint: mvn
    args: ["appengine:deploy"]
timeout: 1800s